---
# defaults file for setup-mq
param_mq:
  src: http://<MQ_SRC_LOCATION>
  tar_file: mqadv_dev92_linux_x86-64.tar.gz
  kshell: /bin/ksh
  user:
    name: mqm
    home: /var/mqm
  group: 
    name: mqm
  packages:
    - libselinux-python
    - bc
    - pax
    - rpm-build

  rpm_suffix: '-9.2.0-0.x86_64.rpm'

  prefix: /opt/mqm

  wd: /var/tmp/mq92/

  kernel_params:
    - { name: kernel.shmmni, value: 4096 }
    - { name: kernel.shmall, value: 2097152 }
    - { name: kernel.shmmax, value: 268435456 }
    - { name: kernel.sem, value: '"500 256000 250 1024"' }
    - { name: fs.file-max, value: 524288 }
    - { name: net.ipv4.tcp_keepalive_time, value: 180 }
  limits:
    - { name: mqm.*soft.*nofile, value: mqm soft nofile 10240 }
    - { name: mqm.*hard.*nofile, value: mqm hard nofile 10240 }
    - { name: mqm.*soft.*nproc, value: mqm soft nproc 4096 }
    - { name: mqm.*hard.*nproc, value: mqm hard nproc 4096 }

  log_dir: /var/mqm/log
  data_dir: /var/mqm/data

  required_directories:
  - /opt/mqm
  - /var/mqm
  - "{{ param_mq.log_dir }}"
  - "{{ param_mq.data_dir }}"