apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: snowflake
  name: snowflake 
  namespace: development
spec:
  replicas: 25
  selector:
    matchLabels:
      app: snowflake
  template:
    metadata:
      labels:
        app: snowflake
    spec:
      containers:
      - image: nginx:1.7.5
        name: nginx
        resources:
          limits:
            memory: 256Mi
            cpu: "0.3"
          requests:
            memory: 200Mi
            cpu: "0.2"